### ISSUE TITLE
Tag a new release?

### ISSUE THREAD

**Issue by alancleary** [avillafiorita/jekyll-datapage_gen#109]
Hey there. Thanks for writing this awesome plugin. It's exactly what we've been looking for!

Would you mind putting a new release one rubygems? We need some of the more recent changes that have been pushed but can only install tagged versions via a gemspec file. Thanks!

**Comment by avillafiorita** [comment]
o boy, does time fly by! You are right completely, latest release was 11 months old ... and I just pushed 1.4.0 to rubygems.
thanks for pointing out!

**Comment by alancleary** [comment]
Thanks @avillafiorita!
