### ISSUE TITLE
Another noob question

### ISSUE THREAD

**Issue by kolyafabrika** [avillafiorita/jekyll-datapage_gen#15]
The plugin worked flawlessly on localhost but once I pushed the site to Github the pages created with the plugin seem to be absent.
https://kolyafabrika.github.io/

Catalog -> any item
Did I miss something specific?

**Comment by avillafiorita** [comment]
This is due to a limitation GitHub set for security reasons: only official plugins can be run on GitHub when pushing a site. See https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/.

You need to generate your site locally and then push your site's static files.

**Comment by Sispheor** [comment]
Hi, do I need to push only the `_site` folder?
