### ISSUE TITLE
Linking auto generated links

### ISSUE THREAD

**Issue by geloangelia** [avillafiorita/jekyll-datapage_gen#23]
Page linking is not working on me.

_config.yml

page_gen-dirs: true 
page_gen:
  - data: 'vclist'
    template: 'profile'
    name: 'Name'
    dir: 'vclist'

CODE:

<ul>
{% for list in site.data.vclist %}
  <li><a href="{{ list.Name | datapage_url: 'vclist' }}">{{list.Name}}</a></li>
{% endfor %}
</ul>

**Comment by avillafiorita** [comment]
I checked and it is unrelated to the plugin. Closing the bug.

Fix your baseurl declaration. It should be:

  baseurl: "/mynewsite" # the subpath of your site, e.g. /blog

and not `baseurl: "mynewsite"`, like it is now.

**Comment by geloangelia** [comment]
I did. But the links still not working

https://github.com/geloangelia/mynewsite
