### ISSUE TITLE
Generate nicer URLs

### ISSUE THREAD

**Issue by rayshan** [avillafiorita/jekyll-datapage_gen#3]
Hi, currently if you use a title string, such as "The Awesome Photo", for the name key, the resulting directory structure is `The_Awesome_Photo/index.html`. It would be more friendly to generate `the-awesome-photo/index.html`.

**Comment by avillafiorita** [comment]
Hi - sorry for taking so long... you are right: I have changed the function to generate URLs, which should now follow your suggestion.

**Comment by rayshan** [comment]
No problem. Thank you!
