### ISSUE TITLE
Error in bulding

### ISSUE THREAD

**Issue by iltempe** [avillafiorita/jekyll-datapage_gen#31]
During jekyll building I have this "jekyll 3.5.1 | Error:  undefined method `tr' for nil:NilClass".

**Comment by avillafiorita** [comment]
difficult to tell what is going on without further data.

my best guesses: 

- you did not specify the "name" field in the configuration
- one of the records in your data does not have the field used for generating page names (e.g., if the field used to generate page names is "surname", one record does not have the "surname" field).

**Comment by iltempe** [comment]
thanks! in fact my data are http://mappe.regione.toscana.it/db-webgis/musei/example_postgis.jsp?format=json&_ga=2.50400233.1701934011.1502803639-2104128018.1501614393 that is defined in the web portal as JSON but is not a "real JSON" but instead it seems a GeoJSON. Do you think should be linked with this issue?

**Comment by avillafiorita** [comment]
yes, it seems to be: 

- input data should be an array 
- the "name" field in the configuration file should be an existing key. The one you chose ("id") does not seem to be a valid field (you could try with "codicechiave", for instance)
