### ISSUE TITLE
I want to get data in _includes/hero.html from _data/member.yml

### ISSUE THREAD

**Issue by SanjayJadon** [avillafiorita/jekyll-datapage_gen#33]
Hello, Firstly thanks for share nice plugin...

According to your example I want to include file in your profile.html from _includes/hero.html
like - {% include hero.html %}

in hero.html - How I get data from _data/member.yml
I try this in my _includes/hero.html 
<h1>{{ site.data.member[full_name] }}</h1>

but its not working so please help me out. 

Thanks in advance !!!

**Comment by avillafiorita** [comment]
sorry fot taking so long to get back to you.

I think you should be using:

    {{ page.member.full_name }}

let me know if it solves your problem!
