### ISSUE TITLE
Cannot do groups in generated pages

### ISSUE THREAD

**Issue by RandyMustache** [avillafiorita/jekyll-datapage_gen#35]
I used this plugin to create a staff directory. It has been absolutely flawless, but I was hoping to extend it to be able to create individual pages of grouped items. 

So far I can make a page for each staff member, but I was hoping to also make a page for each state, and have every staff member within the state show. When I try to do that, it only shows one staff member from that state, and their associated data is all broken.

**Comment by avillafiorita** [comment]
... this is know, I know! :-)

We had a similar problem with our website and solved it using liquid 
conditions to filter the data.

That is, you create different pages, one per group, and then run through 
the staff members selecting only those relevant for the specific page.

Something along the lines of:

   {% if member.state == "past" %}

       ....

   {% end %}

A different matter is if you want to *automatically* create one page per 
state (e.g. if you have twenty different states). A quick solution could 
be that of defining another yaml data structure, let us say "states", 
which contains all the values for which you want to generate pages. In 
the layout of the "state" page, you could then loop over the staff 
members and filter like in the previous case.

A more structural solution is extending the syntax of the plugin to 
group over one field in the data. In case, have you got any suggestion 
on the syntax to adopt?

     kind regards
     -a


On 11/29/2017 10:51 PM, Mitchell Smith wrote:
> make a page for each staff member, but I was hoping to also make a 
> page for each state, and have every staff member within the state 
> show. When I try to do that, it only shows one staff member from that stat

-- 
Adolfo Villafiorita
Head of Unit - ICT4G - Fondazione Bruno Kessler
http://ict4g.fbk.eu
adolfo.villafiorita@fbk.eu - +39 0461 314311 - +39 349 6204514

**Comment by avillafiorita** [comment]
... now I see!

I have updated the code to support conditional generation of pages. It should now be possible to generate pages in different subdirectories according to arbitrary boolean conditions you can set in _config.yml.

Have a look at the documentation of `filter_condition` and at the `example` site for more details.

Let me know if it solves your issue, so that I can close it.
