### ISSUE TITLE
jekyll pagemapper 

### ISSUE THREAD

**Issue by KochuraniT** [avillafiorita/jekyll-datapage_gen#42]
i got the error jekyll 3.7.0 | Error: undefined method `gsub' for #<Hash:0x000000058f0318> on rake build command, and the following is my _config.yml file contents:
[_config.txt](https://github.com/avillafiorita/jekyll-datapage_gen/files/1662735/_config.txt)

**Comment by avillafiorita** [comment]
Hi,
the most likely cause is that the field "page" in one of the records in "contentful.spaces.juries.jury" is a hash and not a string.

let me know if this solves your issue!

**Comment by KochuraniT** [comment]
could you give me an example.where i change to make it working in _config.yml file?

**Comment by avillafiorita** [comment]
for the plugin to work, each record in `contentful.spaces.juries.jury` should have a `page` attribute, which must be a string.

I think you have one record in `contentful.spaces.juries.jury` which is a Hash. Two solutions: 

1. you choose another field to generate page names from records. You need to change `name` in `_config.yml` to the name of the field you want to use.

or

2. you make sure each record in `contentful.spaces.juries.jury` has a field `page` and that all `page` fields store a string (and not a Hash).

let me know if it works
