### ISSUE TITLE
jekyll 3.7.2 | Error:  no implicit conversion of Integer into String

### ISSUE THREAD

**Issue by vinrgates** [avillafiorita/jekyll-datapage_gen#43]
```
Configuration file: /Users/usr/Documents/jekyll/my/_config.yml
            Source: /Users/usr/Documents/jekyll/my
       Destination: /Users/usr/Documents/jekyll/my/_site
 Incremental build: enabled
      Generating...
  Liquid Exception: no implicit conversion of Integer into String in /_layouts/post.html
jekyll 3.7.2 | Error:  no implicit conversion of Integer into String
```
I used your example files because I want to see the preview but I got this when trying to run it.
The gem version is 2.7.4

**Comment by avillafiorita** [comment]
The problems seems to be in the _layouts/post.html file, which is not part of the example dir.

The example dir contains a couple of posts which are not necessary and that I will remove in a future release, but the issue does not seem to be related to the plugin.

Let me know if you find the issue.

**Comment by vinrgates** [comment]
Hi, I have post.html file in the layout folder so it should be fine.
Anyway, I got it working now, but I'm not sure what the problem is.
1 thing for sure is when I remove all the code that related to "books.yml" inside the config file it works.

**_config.yml**
```

  - index_files: false
    data: 'books'
    template: 'book'
    name: 'title'
    dir: 'all-books'

  - data: 'books'
    template: 'book'
    name: 'title'
    dir: 'books-i-have-read'
    filter: read

  - data: 'books'
    template: 'book'
    name: 'title'
    dir: 'books-i-have-not-read'
    filter_condition: "record['read'] == false"

  - data: 'books'
    template: 'book'
    name: 'title'
    dir: 'books-by-orwell'
    filter_condition: "record['author'] == 'George Orwell'"

```


and if I try to remove some other things like the `books.yml` only or only some part of the code that related to `books.yml` inside the `_config.yml` I got some error message like this

```
jekyll 3.7.2 | Error:  undefined method `each' for nil:NilClass
```
or
```
jekyll 3.7.2 | Error:  undefined method `tr' for nil:NilClass
```
or
```
jekyll 3.7.2 | Error:  private method `select' called for nil:NilClass
```

Sorry I can't help much, I'm still a newbie.

**Comment by avillafiorita** [comment]
if you got it working I guess I can close the bug, then.
Thanks for the report and the follow up.
