### ISSUE TITLE
Problem with local variable

### ISSUE THREAD

**Issue by barttom** [avillafiorita/jekyll-datapage_gen#5]
Hi!
When i tring build my jekyll project, I get error:
jekyll 2.5.3 | Error:  undefined local variable or method `data_file' for #<Jeky
ll::DataPagesGenerator:0x31dd8b8>

Can You help me with that?

**Comment by jbleuzen** [comment]
I got the same error because the variable is not defined.
But if you setup correctly the plugin in your _config.yml, this error won't prevent you from building your site.

I can provide my working conf if you want.
