### ISSUE TITLE
Use includes in data

### ISSUE THREAD

**Issue by daimz** [avillafiorita/jekyll-datapage_gen#61]
I am trying to use includes inside posts for specific content blocks. When I am testing I just see the include displayed as a string:
`{% include components/blockquote.html copy="This is a test blockquote" %}`

Is it possible to use includes with page_gen and if so how do I get it to not render as a string?

**Comment by avillafiorita** [comment]
[sorry for taking so long to process your request.]

The plugins does not interferes with posts, so I am not quite sure I understand: you should be able to add includes in the templates used by page_gen.
