### ISSUE TITLE
CSV as input?

### ISSUE THREAD

**Issue by lrdj** [avillafiorita/jekyll-datapage_gen#62]
Wondering how difficult it would be to accept csv as the input format?
Or in other words, should I start trying to figure it out or should I stop and find an alternative solution (like scripting a conversion to yml)

**Comment by avillafiorita** [comment]
Hi -
CSV files work out of the box, because Jekyll supports CSV files as _data.
See an example in test_cases/issue-62.

[sorry for taking so long]
