### ISSUE TITLE
Migrate to Jekyll-Plugin GEM? 

### ISSUE THREAD

**Issue by jffrydsr** [avillafiorita/jekyll-datapage_gen#65]
adding the plugin contents into `_plugins` is easy enough but without tests, abstracted class methods, and a `.gemspec` script, the plugin though handy in conception is in a kind of beta. I've forked this repo for my own purposes - processing data_content in `_data` files into an API call ` and on completion realized I'd prefer this as a contained plugin to remove or add easily from `gem` and `_config`. I think several other issues 'like CSV imports' would be resolved as a result too thanks to a more robust and standard architecture. if nothing else, it's a creative commons so I'll gladly credit this properly but I beieve it's worth considering. . . 

oh, and why not `jekyll-page-generator' for a repo/plugin name? 😌

**Comment by avillafiorita** [comment]
Thanks for the suggestions. Migrating to a gem is a good idea: there is in fact an old pull request I should have incorporated some time ago.

You are most welcome to contribute with change requests to address some of the open issues you are mentioning, such as CSV import.

**Comment by avillafiorita** [comment]
Migrated!
