### ISSUE TITLE
build faii required _config change

### ISSUE THREAD

**Issue by alanlivio** [avillafiorita/jekyll-datapage_gen#70]
Hello. 
I recevied the following error:
```
extenal.rb:58:in `block in require_with_graceful_fail'
/var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/external.rb:73:in `rescue in block in require_with_graceful_fail': jekyll-datapage-generator (Jekyll::Errors::MissingDependencyException)
```
My Gemfile was like:
```
group :jekyll_plugins do
  gem 'jekyll-datapage-generator', '~> 1.1'
end
```
My _config was like:
```
plugins:
  - jekyll-datapage-generator
```
It worked when use the following code in _config.yaml:
```
plugins:
  - data_page_generator
```

**Comment by avillafiorita** [comment]
thanks, 
it is clearly an issue with the naming convention: I will fix it.

**Comment by DBHare** [comment]
Thanks.  I am having the same problem trying to include this as a gem.  It was driving me crazy thinking I was doing something wrong.  I was thinking of trying to do it manually as a plug in in the meantime, but presume that it then won't work on my production site which is built by netlify.  Anyway, I really like the concept and hope I can get it to work.  Thanks!

**Comment by avillafiorita** [comment]
Hello, I have fixed the problem, renaming source file and module name. 

Now you need to declare the plugin as:

    plugins:
       - jekyll-datapage-generator

like the Gem name. Better convention, now, but it might cause you (again!) an error in the configuration file.

I am closing this issue: thanks for pointing out the mess in the naming conventions!
