### ISSUE TITLE
Please document the release changes

### ISSUE THREAD

**Issue by ffes** [avillafiorita/jekyll-datapage_gen#77]
Right now it is very hard to know what has changed between various versions. Could you please add a `CHANGELOG` file to the repository to document those changes? Looking at the commit log I noticed that there where breaking changes, but I don't see that documented anywhere. Even digging through the commit log of the README doesn't work because the file has been renamed and changed too much. Luckily it still seems to work for my project though.

**Comment by avillafiorita** [comment]
You are absolutely right. It will come out with release 1.3.0

To answer your question, the breaking change is between version 1.1.0 and 1.2.0 and in more details, it is about the name used to load the gem in =_config.yml=. (So if it works for you, then it means the gem is properly loaded). Quoting the README.org (16th of April, v1.2.0):

> The source file of this generator has been renamed
> =jekyll-datapage-generator.rb=, to make gem and plugin name uniform
> (see https://github.com/avillafiorita/jekyll-datapage_gen/issues/70
> for an explanation).  This should simplify installation as a gem, but
> requires to change the name of the plugin in the =_config.yml= file,
> if you are upgrading from an earlier version.
> 

Having said that, a proper CHANGELOG is the way to go :-)

Thanks for pointing it out!

**Comment by avillafiorita** [comment]
Released version 1.3 with a new CHANGELOG.org file listing the changes. 

Now documentation, gem, and code are again in sync. New released will be documented with the changelog

Thanks for pointing out!
