### ISSUE TITLE
Prefix keys

### ISSUE THREAD

**Issue by Gibbo3771** [avillafiorita/jekyll-datapage_gen#91]
It would be nice to have the ability to prefix keys. I have a json file that contains the key `name`, by default this is reserved for the name of the page.

It would be nice if we could prefix every key with something so there is no conflicts with Jeklly defaults

**Comment by avillafiorita** [comment]
sorry for taking so long.

This is indeed already supported, thanks to a pull request (see https://github.com/avillafiorita/jekyll-datapage_gen/pull/75). 

What you want to use is: `page_data_prefix`

Closing the issue, we can reopen it if you need further support.
