### ISSUE TITLE
Not generating pages

### ISSUE THREAD

**Issue by richibrics** [avillafiorita/jekyll-datapage_gen#93]
Hi, it's the first time I use Jekyll, I tried both to add the .rb in the _plugin folder and adding it to the Gemfile (and then bundle install) but the pages don't appear.

In my _config.yml I have:

```
plugins:
  - jekyll-datapage-generator

data_gen:
  - data: 'sensors'
    name: 'name'
```

and I also have a file in the _data folder named sensors.yml with this content (file: .../project/_data/sensors.yml) :
```
- name: Disk
  compatibility: "mwl"
  description: "Reports volume usage and other disk information"
- name: File
  compatibility: "mwl"
  description: "Reports the content of a specified file"
```

In the verbose log the only relevant entry is: `Jekyll::JekyllDatapageGenerator finished in 6.103e-06 seconds.`

I think I made a mistake in the configuration (and I'm sorry for this).

In the _site folder I haven't a 'sensor' folder.

Thank you

**Comment by richibrics** [comment]
Solved, in _config.yml I was using "data_gen" and not "page_gen".
Sorry for the mess

**Comment by avillafiorita** [comment]
no problem, glad you solved the problem!
-a
